---
kind: pipeline
type: docker
name: default

steps:
  - name: restore cache
    image: meltwater/drone-cache
    pull: "if-not-exists"
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - ./node_modules
        - ./.pnpm-store
    volumes:
      - name: cache
        path: /tmp/cache

  - name: build
    image: gplane/pnpm:9.14
    pull: "if-not-exists"
    commands:
      - pnpm i
      - pnpm build

  - name: rebuild cache
    image: meltwater/drone-cache
    pull: "if-not-exists"
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - ./node_modules
        - ./.pnpm-store
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache
